
spring:
  application:
    name: mall-store
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.105.35.98:3306/flute?serverTimezone=GMT%2B8
    username: root
    password: 123456

logging:
  file:
      path: /Users/mac/Documents/zuyunbo/big/flute/log/
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
    file: "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"
  level:
    com:
     cloud: debug
